//components/MarketAnalysis.tsx: The user interface for the AI
//agent. It handles user input and displays insights generated by Gemini.

import React, { useState } from 'react';
import { getMarketInsight } from '../services/geminiService';
import { TrendResponse } from '../types';

const MarketAnalysis: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [insight, setInsight] = useState<TrendResponse | null>(null);

  const handleAnalyze = async () => {
    if (!topic) return;
    setLoading(true);
    try {
      const res = await getMarketInsight(topic);
      setInsight(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="glass p-12 rounded-[2.5rem] relative overflow-hidden">
      <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 blur-[100px] pointer-events-none" />
      
      <h3 className="text-4xl font-black mb-8 flex items-center gap-4">
        <div className="w-2 h-10 bg-blue-500" />
        AI SYNTHESIS
      </h3>
      
      <div className="flex flex-col md:flex-row gap-4 mb-12">
        <input 
          type="text" 
          placeholder="Query the digital frontier..."
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          className="flex-1 bg-white/5 border border-white/10 rounded-2xl px-6 py-4 outline-none focus:border-blue-500/50 transition-all text-xl font-light"
        />
        <button 
          onClick={handleAnalyze}
          disabled={loading}
          className="bg-white text-black hover:bg-blue-400 transition-colors px-10 py-4 rounded-2xl font-black uppercase tracking-widest text-sm disabled:opacity-50"
        >
          {loading ? 'Synthesizing...' : 'Request Insight'}
        </button>
      </div>

      {insight && (
        <div className="animate-in fade-in slide-in-from-bottom-8 duration-700">
          <div className="grid md:grid-cols-[1fr,1.5fr] gap-8">
            <div className="p-8 rounded-3xl bg-blue-500/5 border border-blue-500/20">
              <p className="text-[10px] uppercase tracking-[0.3em] text-blue-400 mb-4 font-black">Market Trajectory</p>
              <h4 className="text-3xl font-black mb-6 leading-none">{insight.trend}</h4>
              <div className={`inline-flex items-center px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.2em] border ${
                insight.sentiment === 'bullish' ? 'border-green-500/30 text-green-400' :
                insight.sentiment === 'bearish' ? 'border-red-500/30 text-red-400' :
                'border-blue-500/30 text-blue-400'
              }`}>
                {insight.sentiment}
              </div>
            </div>
            <div className="p-8 rounded-3xl bg-white/5 border border-white/10 flex items-center">
              <p className="text-xl leading-relaxed text-white/70 italic font-light">
                "{insight.analysis}"
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MarketAnalysis;
